version: "3.7"

services:
    # Backend API
    face-recognition-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/facerecognition-api
        environment:
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: face-recognition-docker
            POSTGRES_HOST: postgres
        ports:
            - "3000:3000"
    # Postgres
    postgres:
        environment:
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: face-recognition-docker
            POSTGRES_HOST: postgres
        build: ./postgres
        ports:
            - "5432:5432"
